name: Master MC CI/CD
on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup JDK 1.9
      uses: actions/setup-java@v1
      with:
        java-version: 1.9
    - name: Run tests
      run: sbt test
    - name: Build artifacts
      run: sbt dist
    - name: Publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: uladzimirbaklan/lecturer-private-cabinet-messages-controller:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
